# Generated by Django 5.2 on 2025-05-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_is_active"),
        ("user", "0003_user_name_alter_user_groups"),
    ]

    operations = []
