# Generated by Django 5.2 on 2025-05-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("is_offensive", models.BooleanField(default=False)),
                (
                    "offensive_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
