# Generated by Django 5.2 on 2025-05-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-collected_at']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
