# Generated by Django 5.2 on 2025-05-27 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="user_id",
        ),
    ]
