# Generated by Django 5.2 on 2025-05-15 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0003_youtubecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubecomment",
            name="author",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="youtubecomment",
            name="published_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
