# Generated by Django 5.2 on 2025-05-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0003_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
