# Generated by Django 5.2 on 2025-05-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0004_youtubecomment_author_youtubecomment_published_at"),
        ("comment", "0005_comment_is_offensive_comment_offensive_keyword"),
    ]

    operations = []
