# Generated by Django 5.2 on 2025-05-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KeywordPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(db_index=True, max_length=100)),
                (
                    "sensitive",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "약한 필터링"),
                            (2, "기본 필터링"),
                            (3, "강한 필터링"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "악성 댓글에서의 삭제 요청"),
                            (2, "악성으로 잘못 판명난 댓글 복원 요청"),
                        ]
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
